spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mail:
    host: smtp.mailtrap.io
    username: 8f32372b57d9c1
    protocol: smtp
    port: '25'
    password: 45ed21bceeaa59
  datasource:
    password: nE5kMc7JCGNqwDQM
    username: development
    url: jdbc:mysql://localhost:3306/development


jwt:
  public:
    key: classpath:app.pub
  secret: polimi
  expiration:
    time: '90000'
  private:
    key: classpath:app.key
server:
  port: '8080'